[workspace]
authors = ["fkt <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
name = "mybook"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
install-deps = "Rscript -e 'if (!requireNamespace(\"colorblindr\", quietly = TRUE)) remotes::install_github(\"clauswilke/colorblindr\", upgrade = \"never\"); if (!requireNamespace(\"dviz.supp\", quietly = TRUE)) remotes::install_github(\"clauswilke/dviz.supp\", upgrade = \"never\"); if (!requireNamespace(\"ungeviz\", quietly = TRUE)) remotes::install_github(\"wilkelab/ungeviz\", upgrade = \"never\"); if (!requireNamespace(\"ggtextures\", quietly = TRUE)) remotes::install_github(\"clauswilke/ggtextures\", upgrade = \"never\")'"
[dependencies]
quarto = ">=1.8.27,<2"
r-base = ">=4.5.2,<5"
r-knitr = ">=1.51,<2"
r-rmarkdown = ">=2.30,<3"
r-remotes = ">=2.5.0,<3"
r-gganimate = ">=1.0.11,<2"
r-transformr = ">=0.1.5,<1"
r-gifski = ">=1.32.0.2,<2"
r-png = ">=0.1.8,<1"
r-forcats = ">=1.0.1,<2"
r-lubridate = ">=1.9.5,<2"
r-mgcv = ">=1.9.4,<2"
r-tidyr = ">=1.3.2,<2"
r-purrr = ">=1.2.1,<2"
r-broom = ">=1.0.12,<2"
r-emmeans = ">=2.0.1,<3"
r-ggridges = ">=0.5.7,<1"
r-tidybayes = ">=3.0.7,<4"
r-cowplot = "*"
r-shiny = "*"
r-httpuv = "*"
r-commonmark = "*"
r-sourcetools = "*"
r-xtable = "*"
r-promises = "*"
r-later = "*"
r-otel = "*"
r-rcppeigen = "*"
r-rcpparmadillo = "*"
r-systemfonts = "*"
r-textshaping = "*"
r-ragg = "*"
r-svglite = "*"
r-tidyverse = "*"
r-patchwork = "*"
r-ggforce = "*"
r-ggrepel = "*"
r-sf = "*"
r-ggthemes = "*"
r-gridextra = "*"
r-maps = "*"
r-stanheaders = "*"
r-bh = "*"
r-rcppparallel = "*"
r-rstan = "*"
r-brms = "*"
r-rstanarm = "*"
