name: Deploy Quarto Book to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mybook
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.0
          manifest-path: mybook/pixi.toml

      - name: Install dviz.supp and colorblindr
        run: pixi run Rscript -e 'remotes::install_github("clauswilke/colorblindr"); remotes::install_github("clauswilke/dviz.supp")'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto Book
        run: pixi run quarto render

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: mybook/_book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
